name: Build

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dopplerhq/cli-action@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - run: npm run build
      # - name: Run unit test
      #   run:
      #     echo ${{ secrets.DOPPLER_TOKEN_UAT }} | doppler configure set token --scope ./ &&
      #     doppler run -- sh -c 'NODE_ENV=production NODE_CONFIG_ENV=uat npm run test'
